# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'events.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Events(object):
    def setupUi(self, Events):
        Events.setObjectName("Events")
        Events.resize(375, 262)
        Events.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(Events)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 3, 362, 200))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labName = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labName.setObjectName("labName")
        self.horizontalLayout.addWidget(self.labName)
        self.leName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.leName.setObjectName("leName")
        self.horizontalLayout.addWidget(self.leName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_A = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_A.setObjectName("pb_A")
        self.horizontalLayout_2.addWidget(self.pb_A)
        self.pb_B = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_B.setObjectName("pb_B")
        self.horizontalLayout_2.addWidget(self.pb_B)
        self.pb_C = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_C.setObjectName("pb_C")
        self.horizontalLayout_2.addWidget(self.pb_C)
        self.pb_D = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_D.setObjectName("pb_D")
        self.horizontalLayout_2.addWidget(self.pb_D)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(100, 100))
        self.label.setMouseTracking(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        Events.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Events)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 375, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        Events.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Events)
        self.statusbar.setObjectName("statusbar")
        Events.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(Events)
        self.actionQuit.setObjectName("actionQuit")
        self.actionClear_name_field = QtWidgets.QAction(Events)
        self.actionClear_name_field.setObjectName("actionClear_name_field")
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionClear_name_field)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.labName.setBuddy(self.leName)

        self.retranslateUi(Events)
        QtCore.QMetaObject.connectSlotsByName(Events)

    def retranslateUi(self, Events):
        _translate = QtCore.QCoreApplication.translate
        Events.setWindowTitle(_translate("Events", "Events"))
        self.labName.setText(_translate("Events", "Enter &Name: "))
        self.pb_A.setText(_translate("Events", "A"))
        self.pb_B.setText(_translate("Events", "B"))
        self.pb_C.setText(_translate("Events", "C"))
        self.pb_D.setText(_translate("Events", "D"))
        self.checkBox.setText(_translate("Events", "Do you love Python?"))
        self.label.setText(_translate("Events", "Move the mouse over this label"))
        self.menuFile.setTitle(_translate("Events", "File"))
        self.menuEdit.setTitle(_translate("Events", "Edit"))
        self.actionQuit.setText(_translate("Events", "Quit"))
        self.actionClear_name_field.setText(_translate("Events", "Clear name field"))

