# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'images.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Images(object):
    def setupUi(self, Images):
        Images.setObjectName("Images")
        Images.resize(526, 348)
        self.centralwidget = QtWidgets.QWidget(Images)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-7, 6, 525, 299))
        self.tabWidget.setObjectName("tabWidget")
        self.tabA = QtWidgets.QWidget()
        self.tabA.setObjectName("tabA")
        self.labA = QtWidgets.QLabel(self.tabA)
        self.labA.setGeometry(QtCore.QRect(34, 55, 471, 134))
        font = QtGui.QFont()
        font.setPointSize(60)
        self.labA.setFont(font)
        self.labA.setObjectName("labA")
        self.tabWidget.addTab(self.tabA, "")
        self.tabB = QtWidgets.QWidget()
        self.tabB.setObjectName("tabB")
        self.labB = QtWidgets.QLabel(self.tabB)
        self.labB.setGeometry(QtCore.QRect(37, 59, 445, 134))
        font = QtGui.QFont()
        font.setPointSize(60)
        self.labB.setFont(font)
        self.labB.setObjectName("labB")
        self.tabWidget.addTab(self.tabB, "")
        self.tabC = QtWidgets.QWidget()
        self.tabC.setObjectName("tabC")
        self.labC = QtWidgets.QLabel(self.tabC)
        self.labC.setGeometry(QtCore.QRect(46, 58, 454, 134))
        font = QtGui.QFont()
        font.setPointSize(60)
        self.labC.setFont(font)
        self.labC.setObjectName("labC")
        self.tabWidget.addTab(self.tabC, "")
        Images.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Images)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 526, 25))
        self.menubar.setObjectName("menubar")
        self.menuPictures = QtWidgets.QMenu(self.menubar)
        self.menuPictures.setObjectName("menuPictures")
        Images.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Images)
        self.statusbar.setObjectName("statusbar")
        Images.setStatusBar(self.statusbar)
        self.actionA = QtWidgets.QAction(Images)
        self.actionA.setObjectName("actionA")
        self.actionB = QtWidgets.QAction(Images)
        self.actionB.setObjectName("actionB")
        self.actionC = QtWidgets.QAction(Images)
        self.actionC.setObjectName("actionC")
        self.actionQuit = QtWidgets.QAction(Images)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPictureA = QtWidgets.QAction(Images)
        self.actionPictureA.setObjectName("actionPictureA")
        self.actionPictureB = QtWidgets.QAction(Images)
        self.actionPictureB.setObjectName("actionPictureB")
        self.actionPictureC = QtWidgets.QAction(Images)
        self.actionPictureC.setObjectName("actionPictureC")
        self.menuPictures.addAction(self.actionPictureA)
        self.menuPictures.addAction(self.actionPictureB)
        self.menuPictures.addAction(self.actionPictureC)
        self.menuPictures.addAction(self.actionQuit)
        self.menubar.addAction(self.menuPictures.menuAction())

        self.retranslateUi(Images)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Images)

    def retranslateUi(self, Images):
        _translate = QtCore.QCoreApplication.translate
        Images.setWindowTitle(_translate("Images", "Images"))
        self.labA.setText(_translate("Images", "Apple"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabA), _translate("Images", "A"))
        self.labB.setText(_translate("Images", "Banana"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabB), _translate("Images", "B"))
        self.labC.setText(_translate("Images", "Cherry"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabC), _translate("Images", "C"))
        self.menuPictures.setTitle(_translate("Images", "Pictures"))
        self.actionA.setText(_translate("Images", "A"))
        self.actionB.setText(_translate("Images", "B"))
        self.actionC.setText(_translate("Images", "C"))
        self.actionQuit.setText(_translate("Images", "Quit"))
        self.actionPictureA.setText(_translate("Images", "A"))
        self.actionPictureB.setText(_translate("Images", "B"))
        self.actionPictureC.setText(_translate("Images", "C"))

